### PR TITLE
ReqStrand: Add from_char and strand_symbol

### PR DESCRIPTION
**Pull request by sjackman**
Strand provides strand_symbol.

### CODE REVIEW

**Comment by sjackman** [comment]
Why was `(+)`, `(-)` and empty string chosen as the Display representation for Forward, Reverse, and Unknown? `+`, `-`, and `.` would be more natural and useful to me.

**Comment by sjackman** [comment]
@johanneskoester Gentle nudge. Do you have time to review and merge this PR?

**Comment by johanneskoester** [comment]
Here I am. Sorry for the delay. I have decided to maintain projects on one day per week, in order to get something else done in the rest of the time :-). Looking into this now.

**Comment by johanneskoester** [comment]
> Why was `(+)`, `(-)` and empty string chosen as the Display representation for Forward, Reverse, and Unknown? `+`, `-`, and `.` would be more natural and useful to me.

Mhm, this somehow slipped my attention before. I think changing it to +-. would be fine, and indeed more intuitive. Please just change it. Then, there is no need for the `strand_symbol` method, right?

**Comment by sjackman** [comment]
> Here I am. Sorry for the delay. I have decided to maintain projects on one day per week, in order to get something else done in the rest of the time :-). Looking into this now.

No worries at all. I totally get that, and it's a good idea.

> Mhm, this somehow slipped my attention before. I think changing it to +-. would be fine, and indeed more intuitive. Please just change it. Then, there is no need for the strand_symbol method, right?

Great! I suggest merging this PR first, which introduces no backwards incompatible API changes. I'll open a second PR to change the behaviour.

**Comment by sjackman** [comment]
Gentle bump

**Comment by johanneskoester** [comment]
Sorry again :-).

**Comment by johanneskoester** [comment]
Wow, this is really a late merge. We do need more people with merge rights here.

**Comment by sjackman** [comment]
> Wow, this is really a late merge. We do need more people with merge rights here.

That's okay. I've been there, as a maintainer. Thanks for merging, Johannes!

**Comment by sjackman** [comment]
My colleague @pmarks has commit rights to this repo, so I'll ping him next time!

**Pull request merged**
