### PR TITLE
 add Alignment type from rust-bio

### PR DESCRIPTION
**Pull request by pmarks**

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Wait, there is no ci testing here yet. I think this won't build because the doctest of pretty uses something from rust-bio.

**Review by johanneskoester — CHANGES_REQUESTED** [review]
Ok, testing activated. Can you commit something?

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thanks! I guess I should release a new version of rust-bio-types, right? Or do you want to add more before I release?

**Comment by pmarks** [comment]
I don't have anything else to add right now.  A release would be great so that we can have rust-htslib and rust-bio use the released version.

At some point I'l sit down and think about other things that make sense to put here, but that might be a while.

**Comment by johanneskoester** [comment]
Done!

**Pull request merged**
